# This is a basic workflow to help you get started with Actions

name: CI-first-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stage1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script in stage1
        run: echo "Hello, world! from stage1"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script in stage1

        run: |
          echo "Add other actions to build, from stage1"
          echo "test, and deploy your project. from stage1"

  stage2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script in stage2
        run: echo "Hello, world! from stage2"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script in stage2
        run: |
          echo "Add other actions to build, from stage2"
          echo "test, and deploy your project. from stage2"
