# pipeline name
name: Deploy Terraform

# to start pipeline on event basis 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# jobs means stages
jobs:
  terraform:  #job name

    # online server provided by github to run application code 
    runs-on: ubuntu-latest

    env:  #env variable to use while runing pipeline
      TF_VERSION: 1.1.0  # Specify your Terraform version here
      TF_WORKING_DIR: . # Path to your Terraform code directory

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Specify your AWS region here


    - name: Run a multi-line script in stage1
      run: |
        ls -la 
        pwd
        tree

    - name: Initialize Terraform
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        pwd
        ls -la
        terraform init

    - name: Validate Terraform
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform validate

    - name: Plan Terraform
      id: plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -out=tfplan
      
    # - name: apply Terraform
    #   if: github.ref == 'refs/heads/master'  # Only apply on the main branch
    #   working-directory: ${{ env.TF_WORKING_DIR }}
    #   run: terraform apply -auto-approve tfplan
